site_name: 'Tock'
site_description: 'Pour construire aisément vos prochains bots'
site_author: 'Tock'
site_url: 'https://theopenconversationkit.github.io/tock/fr'
repo_name: 'tock'
repo_url: 'https://github.com/theopenconversationkit/tock'
edit_uri: ''
nav:
  - 'Vue d`ensemble': 'index.md'
  - 'Table des matières': 'toc.md'
  - 'Découvrir Tock': # Guides / Découvrir
      - 'Créer son premier bot': 'guide/studio.md'
      - 'Configurer Slack': 'guide/slack.md'
      - 'Configurer Messenger': 'guide/messenger.md'
      - 'Programmer des parcours': 'guide/api.md'
      - 'Déployer avec Docker': 'guide/plateforme.md'
  - 'Utiliser Tock':
      - 'Concepts': 'utilisateur/concepts.md'
      - 'Tock Studio': 'utilisateur/studio.md'
      - 'Bot multicanal': 'utilisateur/canaux.md'
      - 'Bot multilingue': 'utilisateur/i18n.md'
  - 'Développer avec Tock':
      - 'Modes disponibles': 'dev/modes.md'
      - 'Tock Bot API': 'dev/bot-api.md'
      - 'Tock Bot intégré': 'dev/bot-integre.md'
      - 'Connecteurs': 'dev/connecteurs.md'
      - 'i18n': 'dev/i18n.md'
      - 'Liste des APIs': 'dev/api.md'
      - 'Exemples de code': 'dev/exemples-code.md'
  - 'Administrer Tock':
      - 'Architecture': 'admin/architecture.md'
      - 'Installation': 'admin/installation.md'
      - 'Sécurité': 'admin/securite.md'
      - 'Disponibilité': 'admin/disponibilite.md'
      - 'Supervision': 'admin/supervision.md'
      - 'Cloud': 'admin/cloud.md'
  - 'A propos':
      - 'Pourquoi Tock': 'apropos/pourquoi.md'
      - 'Vitrine utilisateurs': 'apropos/vitrine.md'
      - 'Ressources': 'apropos/ressources.md'
      - 'Nous contacter': 'apropos/contact.md'
      - 'Communauté': 'apropos/communaute.md'
      - 'Contribuer': 'apropos/contribuer.md'
      - 'Emploi': 'apropos/emploi.md'
  - '🇫🇷 🇬🇧': 'https://theopenconversationkit.github.io/tock/en/'

theme:
  name: 'material'
  language: 'fr'
  logo: 'assets/images/logo.svg'
  favicon: 'img/favicon.png'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
copyright: 'Copyright &copy; 2017/2019 Tock'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/theopenconversationkit/tock'
  search:
    language: 'fr'